### ISSUE TITLE
`gulp build` fails with an error

### ISSUE THREAD

**Issue by hlide** [chartjs/chartjs-plugin-datalabels#1]
GULP fails to build.

I installed GULP through `npm install gulp` in the root directory.

Windows 10 64-bit:
- Node.js version: v6.11.1
- NPM version: 3.10.10
- GULP CLI & Local versions: 3.9.1 

When I type `gulp build` in the root directory, I get:
```
C:\GIT\chartjs-plugin-datalabels>gulp build
module.js:471
    throw err;
    ^

Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\GIT\chartjs-plugin-datalabels\gulpfile.js:3:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

I was hoping to get it as Chart.js pie or bar fail to draw labels inside or outside (I want their percent values displayed so I can print them) but it looks as if that plugin is not supported any longer.

**Comment by simonbrunel** [comment]
It works for me on Windows 10 64-bit +Node 6.9.2 + npm 3.10.9 + Gulp 3.9.1:

    > git clone git@github.com:chartjs/chartjs-plugin-datalabels.git
    > cd chartjs-plugin-datalabels
    > npm install
    > gulp build

This plugin is pretty new and requires Chart.js 2.7 which is not released yet (so you will also have to build it from master). Definitely not ready for production but any help testing this plugin is of course appreciated :)

**Comment by hlide** [comment]
I was able to build after manually 'npm install'-ed any missing requirements before running `gulp build`. I already did build Chart.js from github (master branch) since it was the only way to get `chart.bundle.min.js`. I must admit I had some warnings but so far I'm able to use `chart.bundle.min.js` and yours.

**Comment by simonbrunel** [comment]
`npm install` takes care of all dependencies, even `gulp`.

What kind of warnings did you see when building?

**Comment by hlide** [comment]
Another thing due to my first time dealing with Node.js. It looks like when you open a console, you need to reinstall gulp and I didn't try to build first Chart.js then yours in the same console.

**Comment by hlide** [comment]
One example for your plugin:
```
C:\GIT\chartjs-plugin-datalabels>npm install gulp-file
chartjs-plugin-datalabels@0.1.0 C:\GIT\chartjs-plugin-datalabels
+-- UNMET PEER DEPENDENCY chart.js@>= 2.7.0 < 3
`-- gulp-file@0.3.0
```

**Comment by simonbrunel** [comment]
You don't need to install each dependencies manually, simply run `npm install` in the root folder.

`UNMET PEER DEPENDENCY chart.js@>= 2.7.0 < 3` warning means that if you create a Node.js project that depends on `chartjs-plugin-datalabels`, then your project also needs to depends on `chart.js` at a version between 2.7.0 and 3. But since you are not creating any project and directly build this plugin, you don't need to care about that warning.

**Comment by hlide** [comment]
I retried to install gulp (`npm install gulp`), here is what I got:
```
C:\GIT>npm install gulp
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
C:\GIT
`-- gulp@3.9.1
  +-- archy@1.0.0
  +-- chalk@1.1.3
  | +-- ansi-styles@2.2.1
  | +-- escape-string-regexp@1.0.5
  | +-- has-ansi@2.0.0
  | | `-- ansi-regex@2.1.1
  | +-- strip-ansi@3.0.1
  | `-- supports-color@2.0.0
  +-- deprecated@0.0.1
  +-- gulp-util@3.0.8
  | +-- array-differ@1.0.0
  | +-- array-uniq@1.0.3
  | +-- beeper@1.1.1
  | +-- dateformat@2.0.0
  | +-- fancy-log@1.3.0
  | | `-- time-stamp@1.1.0
  | +-- gulplog@1.0.0
  | | `-- glogg@1.0.0
  | +-- has-gulplog@0.1.0
  | | `-- sparkles@1.0.0
  | +-- lodash._reescape@3.0.0
  | +-- lodash._reevaluate@3.0.0
  | +-- lodash._reinterpolate@3.0.0
  | +-- lodash.template@3.6.2
  | | +-- lodash._basecopy@3.0.1
  | | +-- lodash._basetostring@3.0.1
  | | +-- lodash._basevalues@3.0.0
  | | +-- lodash._isiterateecall@3.0.9
  | | +-- lodash.escape@3.2.0
  | | | `-- lodash._root@3.0.1
  | | +-- lodash.keys@3.1.2
  | | | +-- lodash._getnative@3.9.1
  | | | +-- lodash.isarguments@3.1.0
  | | | `-- lodash.isarray@3.0.4
  | | +-- lodash.restparam@3.6.1
  | | `-- lodash.templatesettings@3.1.1
  | +-- multipipe@0.1.2
  | | `-- duplexer2@0.0.2
  | |   `-- readable-stream@1.1.14
  | +-- object-assign@3.0.0
  | +-- replace-ext@0.0.1
  | +-- through2@2.0.3
  | | +-- readable-stream@2.3.3
  | | | +-- core-util-is@1.0.2
  | | | +-- inherits@2.0.3
  | | | +-- isarray@1.0.0
  | | | +-- process-nextick-args@1.0.7
  | | | +-- safe-buffer@5.1.1
  | | | +-- string_decoder@1.0.3
  | | | `-- util-deprecate@1.0.2
  | | `-- xtend@4.0.1
  | `-- vinyl@0.5.3
  |   +-- clone@1.0.2
  |   `-- clone-stats@0.0.1
  +-- interpret@1.0.3
  +-- liftoff@2.3.0
  | +-- extend@3.0.1
  | +-- findup-sync@0.4.3
  | | +-- detect-file@0.1.0
  | | | `-- fs-exists-sync@0.1.0
  | | +-- is-glob@2.0.1
  | | | `-- is-extglob@1.0.0
  | | +-- micromatch@2.3.11
  | | | +-- arr-diff@2.0.0
  | | | | `-- arr-flatten@1.1.0
  | | | +-- array-unique@0.2.1
  | | | +-- braces@1.8.5
  | | | | +-- expand-range@1.8.2
  | | | | | `-- fill-range@2.2.3
  | | | | |   +-- is-number@2.1.0
  | | | | |   +-- randomatic@1.1.7
  | | | | |   | +-- is-number@3.0.0
  | | | | |   | | `-- kind-of@3.2.2
  | | | | |   | `-- kind-of@4.0.0
  | | | | |   `-- repeat-string@1.6.1
  | | | | +-- preserve@0.2.0
  | | | | `-- repeat-element@1.1.2
  | | | +-- expand-brackets@0.1.5
  | | | | `-- is-posix-bracket@0.1.1
  | | | +-- extglob@0.3.2
  | | | +-- filename-regex@2.0.1
  | | | +-- kind-of@3.2.2
  | | | | `-- is-buffer@1.1.5
  | | | +-- normalize-path@2.1.1
  | | | | `-- remove-trailing-separator@1.0.2
  | | | +-- object.omit@2.0.1
  | | | | +-- for-own@0.1.5
  | | | | `-- is-extendable@0.1.1
  | | | +-- parse-glob@3.0.4
  | | | | +-- glob-base@0.3.0
  | | | | | `-- glob-parent@2.0.0
  | | | | `-- is-dotfile@1.0.3
  | | | `-- regex-cache@0.4.3
  | | |   +-- is-equal-shallow@0.1.3
  | | |   `-- is-primitive@2.0.0
  | | `-- resolve-dir@0.1.1
  | |   +-- expand-tilde@1.2.2
  | |   `-- global-modules@0.2.3
  | |     +-- global-prefix@0.1.5
  | |     | +-- ini@1.3.4
  | |     | `-- which@1.2.14
  | |     |   `-- isexe@2.0.0
  | |     `-- is-windows@0.2.0
  | +-- fined@1.1.0
  | | +-- expand-tilde@2.0.2
  | | | `-- homedir-polyfill@1.0.1
  | | |   `-- parse-passwd@1.0.0
  | | +-- is-plain-object@2.0.4
  | | | `-- isobject@3.0.1
  | | +-- object.defaults@1.1.0
  | | | +-- array-each@1.0.1
  | | | +-- array-slice@1.0.0
  | | | +-- for-own@1.0.0
  | | | | `-- for-in@1.0.2
  | | | `-- isobject@3.0.1
  | | +-- object.pick@1.2.0
  | | | `-- isobject@2.1.0
  | | |   `-- isarray@1.0.0
  | | `-- parse-filepath@1.0.1
  | |   +-- is-absolute@0.2.6
  | |   | `-- is-relative@0.2.1
  | |   |   `-- is-unc-path@0.1.2
  | |   |     `-- unc-path-regex@0.1.2
  | |   +-- map-cache@0.2.2
  | |   `-- path-root@0.1.1
  | |     `-- path-root-regex@0.1.2
  | +-- flagged-respawn@0.3.2
  | +-- lodash.isplainobject@4.0.6
  | +-- lodash.isstring@4.0.1
  | +-- lodash.mapvalues@4.6.0
  | +-- rechoir@0.6.2
  | `-- resolve@1.3.3
  |   `-- path-parse@1.0.5
  +-- minimist@1.2.0
  +-- orchestrator@0.3.8
  | +-- end-of-stream@0.1.5
  | | `-- once@1.3.3
  | |   `-- wrappy@1.0.2
  | +-- sequencify@0.0.7
  | `-- stream-consume@0.1.0
  +-- pretty-hrtime@1.0.3
  +-- semver@4.3.6
  +-- tildify@1.2.0
  | `-- os-homedir@1.0.2
  +-- v8flags@2.1.1
  | `-- user-home@1.1.1
  `-- vinyl-fs@0.3.14
    +-- defaults@1.0.3
    +-- glob-stream@3.1.18
    | +-- glob@4.5.3
    | | `-- inflight@1.0.6
    | +-- glob2base@0.0.12
    | | `-- find-index@0.1.1
    | +-- minimatch@2.0.10
    | | `-- brace-expansion@1.1.8
    | |   +-- balanced-match@1.0.0
    | |   `-- concat-map@0.0.1
    | +-- ordered-read-streams@0.1.0
    | +-- through2@0.6.5
    | | `-- readable-stream@1.0.34
    | `-- unique-stream@1.0.0
    +-- glob-watcher@0.0.6
    | `-- gaze@0.5.2
    |   `-- globule@0.1.0
    |     +-- glob@3.1.21
    |     | +-- graceful-fs@1.2.3
    |     | `-- inherits@1.0.2
    |     +-- lodash@1.0.2
    |     `-- minimatch@0.2.14
    |       +-- lru-cache@2.7.3
    |       `-- sigmund@1.0.1
    +-- graceful-fs@3.0.11
    | `-- natives@1.1.0
    +-- mkdirp@0.5.1
    | `-- minimist@0.0.8
    +-- strip-bom@1.0.0
    | +-- first-chunk-stream@1.0.0
    | `-- is-utf8@0.2.1
    +-- through2@0.6.5
    | `-- readable-stream@1.0.34
    |   +-- isarray@0.0.1
    |   `-- string_decoder@0.10.31
    `-- vinyl@0.4.6
      `-- clone@0.2.0

npm WARN enoent ENOENT: no such file or directory, open 'C:\GIT\package.json'
npm WARN GIT No description
npm WARN GIT No repository field.
npm WARN GIT No README data
npm WARN GIT No license field.

C:\GIT>npm ls graceful-fs
C:\GIT
+-- gulp@3.9.1
| `-- vinyl-fs@0.3.14
|   +-- glob-watcher@0.0.6
|   | `-- gaze@0.5.2
|   |   `-- globule@0.1.0
|   |     `-- glob@3.1.21
|   |       `-- graceful-fs@1.2.3
|   `-- graceful-fs@3.0.11
`-- npm@5.3.0
  `-- graceful-fs@4.1.11
```
I made it on my GIT folder which contains all the git repositories so the last warnings are normal.

Is it normal that we have the first warnings? I had them when dealing with both `Char.js` (first to be built) and `chartjs-plugin-datalabels` (second to be built - gulp was absent so I needed to install it again).

**Comment by simonbrunel** [comment]
Don't worry about these warnings, I will check which modules need to be updated, but right now there is no repercussion on the generated `chartjs-plugin-datalabels*.js`.

About `gulp`, you don't need to install it manually but simply run `npm install` in `C:\GIT\chartjs-plugin-datalabels`, then the `gulp` command should become available. You only have to do that one time after cloning the project. If the project dependencies are changed, you will need to do `npm update` in the same folder.

**Comment by simonbrunel** [comment]
You might also need to install the `gulp-cli` globally: `npm install gulp-cli -g`

**Comment by simonbrunel** [comment]
@hlide any progress, can we close this ticket? FYI, you don't need to build this plugin anymore, you can directly grab the [development build](https://master--chartjs-plugin-datalabels.netlify.com/chartjs-plugin-datalabels.js) ([minified](https://master--chartjs-plugin-datalabels.netlify.com/chartjs-plugin-datalabels.min.js)).

**Comment by hlide** [comment]
sure, let us close it
