### ISSUE TITLE
helpers$1.extend is not a function

### ISSUE THREAD

**Issue by mikeover** [chartjs/chartjs-plugin-datalabels#172]
Trying to run this with `chartjs-lambda` and `ChartjsNodeCanvas`, everything was working but just requiring `chartjs-plugin-datalabels` blows up with:

```
TypeError: helpers$1.extend is not a function
    at /Users/mike/ds/chartjs-lambda/node_modules/chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels.js:585:11
    at /Users/mike/ds/chartjs-lambda/node_modules/chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels.js:8:81
    at Object.<anonymous> (/Users/mike/ds/chartjs-lambda/node_modules/chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels.js:11:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module._require.o.require (/Users/mike/ds/chartjs-lambda/serverless_sdk/index.js:9:91381)
    at require (internal/modules/cjs/helpers.js:25:18)
    at fresh (/Users/mike/ds/chartjs-lambda/node_modules/fresh-require/index.js:9:13)
    at chartCallback (/Users/mike/ds/chartjs-lambda/chartjs-lambda.js:96:30)
    at new CanvasRenderService (/Users/mike/ds/chartjs-lambda/node_modules/chartjs-node-canvas/src/index.ts:50:4)
    at renderChartWithChartJS (/Users/mike/ds/chartjs-lambda/chartjs-lambda.js:101:31)
    at module.exports.renderChart (/Users/mike/ds/chartjs-lambda/chartjs-lambda.js:106:24)
    at /Users/mike/ds/chartjs-lambda/serverless_sdk/index.js:9:89206
    at resolve (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:708:30)
    at Promise._execute (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:103:10)
    at AwsInvokeLocal.invokeLocalNodeJs (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:661:12)
    at AwsInvokeLocal.invokeLocal (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:167:19)
    at AwsInvokeLocal.tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
```

package.json:
```
{
  "name": "chartjs-lambda",
  "version": "0.0.1",
  "description": "Sample project showing how to run ChartJS inside of AWS lambda",
  "dependencies": {
    "canvas-prebuilt": "^2.0.0-alpha.13",
    "chart.js": "^3.0.0-alpha",
    "chartjs-node-canvas": "^3.0.6",
    "chartjs-plugin-datalabels": "^0.7.0",
    "debug": "^4.1.0"
  }
}
```

My lambda function:
```
'user strict';

const debug = require('debug');
const freshRequire = require('fresh-require');
const fs = require('fs');
const { CanvasRenderService } = require('chartjs-node-canvas');
const ChartDataLabels = require('chartjs-plugin-datalabels');

randomScalingFactor = () => {
  return Math.ceil(Math.random() * 100);
};

async function renderChartWithChartJS() {
  const width = 400;
  const height = 400;
  const configuration = {
  // ...
  };
  const chartCallback = (ChartJS) => {
    ChartJS.defaults.responsive = true;
    ChartJS.defaults.maintainAspectRatio = false;
  };
  const canvasRenderService = new CanvasRenderService(width, height, chartCallback);
  return await canvasRenderService.renderToBuffer(configuration);
}

module.exports.renderChart = async function(event, context, callback) {
  const buffer = await renderChartWithChartJS();
  fs.writeFileSync('/tmp/chartjs-lambda.png', buffer);

  const response = {
    statusCode: 200,
    body: null
  };

  callback(null, response);
}
```

**Comment by mikeover** [comment]
Changed to ChartJS version 2.7.0 and it worked
