### ISSUE TITLE
Build failed: TypeError: (0 , n.merge) is not a function at Object.<anonymous> (chartjs-plugin-datalabels.esm.js:579:1)

### ISSUE THREAD

**Issue by huqedato** [chartjs/chartjs-plugin-datalabels#385]
When I build it  with Parcel the entire build fails: _TypeError: (0 , n.merge) is not a function
    at Object.<anonymous> (chartjs-plugin-datalabels.esm.js:579:1)_

Package versions:
chartjs-plugin-datalabels@2.2.0
chart.js@4.3.0
parcel@2.8.2

**Comment by xdarov** [comment]
problem not solved?

**Comment by xdarov** [comment]
parcel build --no-scope-hoist
it worked for me

**Comment by simonbrunel** [comment]
@huqedato did you try the solution suggested by @xdarov? If it's not working, please provide a repository that reproduces your issue.

**Comment by kokarn** [comment]
I can confirm `--no-scope-hoist` fixed a similar issue for me. Any idea why this would be needed?
