### ISSUE TITLE
Pie Chart Labels are broken

### ISSUE THREAD

**Issue by MasterCash** [chartjs/chartjs-plugin-datalabels#387]
It looks like that the labels are broken with Pie Chart labels in the latest ChartJs

```
chartjs-plugin-datalabels.esm.js:118 Uncaught TypeError: Cannot read properties of null (reading 'x')
    at orient (chartjs-plugin-datalabels.esm.js:118:19)
    at Object.fallback [as positioner] (chartjs-plugin-datalabels.esm.js:342:13)
    at coordinates (chartjs-plugin-datalabels.esm.js:838:21)
    at Object.draw (chartjs-plugin-datalabels.esm.js:1009:18)
    at Object.afterDatasetsDraw (chartjs-plugin-datalabels.esm.js:1302:12)
    at callback (helpers.core.ts:109:15)
    at PluginService._notify (core.plugins.js:60:11)
    at PluginService.notify (core.plugins.js:42:25)
    at Chart.notifyPlugins (core.controller.js:1148:26)
    at Chart._drawDatasets (core.controller.js:787:10)
```

_Originally posted by @tedik123 in https://github.com/chartjs/chartjs-plugin-datalabels/issues/380#issuecomment-1631647819_

There is a PR #380 which looks like it fixes this problem, according to the PR it is an issue where `instanceof` no longer works in newer versions of ChartJs

**Comment by MasterCash** [comment]
would be really great to get this fixed.

**Comment by simonbrunel** [comment]
@MasterCash If `instanceof` does not work, it's probably because your project compiles 2 different versions of Chart.js. If you are sure that it's not the case, please provide a codepen that reproduces this issue. Note that PR #380 does provide a proper fix.

**Comment by COV-GIS** [comment]
I just ran into the same error. A few months ago I updated a couple apps to chart js 4.x using data labels 2.2.0. Everything was working fine in dev and deployment until yesterday when the doughnut chart with labels failed to render and throws the above error. There has been no code changes. Additionally, bar chart labels are also having alignment issues but throw no errors. None of the alignment options are working.

![image](https://github.com/chartjs/chartjs-plugin-datalabels/assets/14297903/22a6212e-4b41-480c-8a30-d4f6a8ba235e)
They were just centered horizontally by default. And again...no option can effect the position.

This is possibly (???) a jsdelivr +esm issue as my refactor went module with imports like:

```typescript
import {
  Chart,
  DoughnutController,
  ArcElement,
  Title,
  Tooltip,
} from 'https://cdn.jsdelivr.net/npm/chart.js@4.3.0/+esm';
import ChartDataLabels from 'https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.2.0/+esm';
```

I'm removing labels as a temporary fix. And any suggestions as to what may be causing this would be appreciated.

My charts config is complex and data is dynamic so not good for reproduction. I'm going to keep digging into this. And see if I can get a pen up to reproduce.

**Comment by muhismail015** [comment]
> I just ran into the same error. A few months ago I updated a couple apps to chart js 4.x using data labels 2.2.0. Everything was working fine in dev and deployment until yesterday when the doughnut chart with labels failed to render and throws the above error. There has been no code changes. Additionally, bar chart labels are also having alignment issues but throw no errors. None of the alignment options are working.
> 
> ![image](https://github.com/chartjs/chartjs-plugin-datalabels/assets/14297903/22a6212e-4b41-480c-8a30-d4f6a8ba235e) They were just centered horizontally by default. And again...no option can effect the position.
> 
> This is possibly (???) a jsdelivr +esm issue as my refactor went module with imports like:
> 
> import {
>   Chart,
>   DoughnutController,
>   ArcElement,
>   Title,
>   Tooltip,
> } from 'https://cdn.jsdelivr.net/npm/chart.js@4.3.0/+esm';
> import ChartDataLabels from 'https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.2.0/+esm';
> I'm removing labels as a temporary fix. And any suggestions as to what may be causing this would be appreciated.
> 
> My charts config is complex and data is dynamic so not good for reproduction. I'm going to keep digging into this. And see if I can get a pen up to reproduce.

got the same problem on stacked bar chart, the first chart create is normal, but the second or many the align text center is broken, i tried many solution still same.

are you find the solution or how to fix this?

![Image](https://github.com/user-attachments/assets/b9fa75c2-8025-41f2-9c4b-442e26ab8905)

![Image](https://github.com/user-attachments/assets/441ab039-4b0e-434d-9597-9166f2e757ac)

my code:
```js
    const chartJSNodeCanvas = new ChartJSNodeCanvas({
      width: 1184,
      height: 473,
      backgroundColour: "white",
      chartCallback: (ChartJS) => {
        ChartJS.register(ChartDataLabels);
      },
    });

    const config = {
      type: "bar",
      data: {
        labels: slicedLabels,
        datasets: [
          {
            label: "Kategori 1",
            data: slicedData1,
            backgroundColor: "#18A73A",
          },
          {
            label: "Kategori 2",
            data: slicedData2,
            backgroundColor: "#AD1F1F",
          },
        ],
      },
      options: {
        responsive: true,
        plugins: {
          legend: { display: false },
          datalabels: {
            display: true,
            color: "red",
            font: { weight: 500, size: 20 },
            anchor: "center",
            align: "center",
            offset: 0,
            clamp: true,
            clip: false,
            textAlign: "start",
            formatter: (value) => value,
          },
        },
        scales: {
          x: {
            stacked: true,
            ticks: {
              color: "black",
              font: { size: 16, weight: 500 },
            },
            grid: {
              display: false,
            },
          },
          y: {
            stacked: true,
            display: true,
            // beginAtZero: true,
            // min: 0,
          },
        },
      },
      plugins: [ChartDataLabels],
    };
```

**Comment by DotoPototo** [comment]
I posted my own understanding & solution in #411 if it helps anyone
