### ISSUE TITLE
Crashes on Chart.js 4.4.1 and 4.4.0

### ISSUE THREAD

**Issue by igordata** [chartjs/chartjs-plugin-datalabels#411]
Hello,

I'm trying to make it work with Chart.js server side, node.js 19 and chartjs-plugin-datalabels version 2.2.0

Chart.js 4.4.1 or 4.4.0 - same error

here is the log:

```
someProject\node_modules\chartjs-plugin-datalabels\dist\chartjs-plugin-datalabels.js:121
  var x0 = origin.x;
                  ^

TypeError: Cannot read properties of null (reading 'x')
    at orient (someProject\node_modules\chartjs-plugin-datalabels\dist\chartjs-plugin-datalabels.js:121:19)
    at Object.fallback [as positioner] (someProject\node_modules\chartjs-plugin-datalabels\dist\chartjs-plugin-datalabels.js:345:13)
    at coordinates (someProject\node_modules\chartjs-plugin-datalabels\dist\chartjs-plugin-datalabels.js:841:21)
    at Object.draw (someProject\node_modules\chartjs-plugin-datalabels\dist\chartjs-plugin-datalabels.js:1012:18)
    at Object.afterDatasetsDraw (someProject\node_modules\chartjs-plugin-datalabels\dist\chartjs-plugin-datalabels.js:1305:12)
    at callback (file:///someProject/node_modules/chart.js/dist/chunks/helpers.segment.js:79:19)
    at PluginService._notify (file:///someProject/node_modules/chart.js/dist/chart.js:5073:17)
    at PluginService.notify (file:///someProject/node_modules/chart.js/dist/chart.js:5056:29)
    at Chart.notifyPlugins (file:///someProject/node_modules/chart.js/dist/chart.js:6338:30)
    at Chart._drawDatasets (file:///someProject/node_modules/chart.js/dist/chart.js:6081:14)
```
Node.js v19.9.0

Just in case:
```
  "dependencies": {
    "axios": "^1.6.7",
    "canvas": "2.10.2",
    "chart.js": "4.4.0",
    "chartjs-plugin-datalabels": "^2.2.0",
    "docx": "^8.5.0"
  }
```
Any help will be appreciated!

**Comment by igordata** [comment]
I feel stuck. 
Any ideas? 😅

**Comment by divyavanmahajan** [comment]
Hi,
This appears to be a bug in chartjs-plugin-datalabels.
In the code - there is a function getPositioner() which returns the positioned depending on the class of the element. However - the code imports chart.js - and the element was created by another part of the code which imported chart.cjs - Javascript thinks the two are different classes - and this causes the code to fail.

You can troubleshoot this in the browser by setting a breakpoint in getPositioner(). Compare Object.getPrototypeOf(el) with chart_js.ArcElement - the constructor shows the source files are different.

## Workaround
Assuming you are using ESM (import/export), change your import from
```js
import ChartJSDataLabel from 'chartjs-plugin-datalabels';
```
to 
```js
import ChartJSDataLabel from 'chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels.esm.js';
```

**Note: You must change this in all files that import chartjs-plugin-datalabels.**

**Comment by igordata** [comment]
A stacked bar chart works though. Which is weird.

**Comment by timothyallan** [comment]
Frustrating. When trying the above .ems import trick, I kept getting import errors from the component trying to import chart.js files. I finally just took the whole datalabels .esm.js file, made a new .js file, copied it into my project locally, and imported it directly. Works great... now I just need to keep an eye out for npm updates when this bug gets fixed.

**Comment by DotoPototo** [comment]
So based off [simonbrunel](https://github.com/chartjs/chartjs-plugin-datalabels/pull/380#issuecomment-1647393679) response to the PR, looks like the fix is to ensure the plugin depends on the exact same Chart.js package used to create the chart.

I had to do some digging to figure this all out, but this is my understanding of it:

We know we get the `null (reading 'x')` issue because the plugin fails to identify the chart elements as `ArcElement` instances. 

Even if you only have one `chart.js` instance/version on disk, with how pre-bundling (`vite` in my case) works you can sometimes end up with multiple instances of `chart.js` being loaded into memory. The plugin checks `if (el instanceof ArcElement)` but if the `ArcElement` class imported by the plugin is from a _different_ `chart.js` instance then the check fails, because `instanceof` doesn't equate them to being the same, they really are separate instances in this case.

I.e. in my project, I have 
```js
import { Chart as ChartJS } from 'chart.js'
```
which `vite` pre-bundles into something like `@/module/chart.js`

But then when this plugin ships its own ESM file which in turn does 
```js
import { ArcElement } from 'chart.js'
```
this bypasses the pre-bundle and you end up with a completely separate `chart.js` module instance loaded. 

We can fix this by telling the bundler to always resolve `chart.js` to the same single instance. So in `vite` we can update the config

```js
// vite.config.js
export default defineConfig({
  // ...
  resolve: {
    alias: {
      'chart.js': fileURLToPath(new URL('./node_modules/chart.js', import.meta.url)),
    },
  },
  // ...
});
```

Now, I don't fully understand why this is _now_ a problem and not before, though I will say that the plugins reliance on `instanceof` seems very fragile and should probably be improved upon.

**Comment by Whobeu** [comment]
> So based off [simonbrunel](https://github.com/chartjs/chartjs-plugin-datalabels/pull/380#issuecomment-1647393679) response to the PR, looks like the fix is to ensure the plugin depends on the exact same Chart.js package used to create the chart.

When I got this notification this morning it had me puzzled as I have not had an issue with CommonJS and I have mirrored ESM projects but had not tested them. Sure enough, CommonJS still works fine but my ESM implementations had the same issue. The thing was the ESM modules did work correctly in the past and apparently I had done some modifications that undid the fix. Reading this thread again I realized what the fix was and that at some point I must have deleted it. What @divyavanmahajan recommended above solves the problem as it appears to be an issue with chartjs-plugin-datalabels and not Chart.js:

`import ChartJSDataLabel from 'chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels.esm.js';`

I should also note that when I import Chart.js I use the following:

`import { Chart as ChartJS } from 'chart.js/auto'`

Not the bare "chart.js".

**Comment by matias49** [comment]
Hello there.

Just pumping up this issue as I had the same problem with the Symfony AssetMapper, and I found some similar issue happening in Rails 7. Their workaround worked on my side for the 'doughnut' chart: https://stackoverflow.com/questions/74449004/get-chart-js-to-work-with-importmap-in-rails-7

`importmap.php`
```php
<?php
[...]
    'chart.js/helpers' => [
        'version' => '4.5.0',
    ],
    'chart.js' => [
        'version' => '4.5.0',
    ],
    'chart.js/auto' => [
        'version' => '4.5.0',
    ],
    'chartjs-plugin-datalabels' => [
        'version' => '2.2.0',
    ],
```
(yes, I have both `chart.js` and `chart.js/auto`, as some charts dont't need the datalabels)

`js_file_controller.js`
```javascript
import {Controller} from '@hotwired/stimulus';
import { Chart, registerables } from "chart.js"
import ChartJSDataLabel from 'chartjs-plugin-datalabels';

/* stimulusFetch: 'lazy' */
export default class extends Controller {

connect() {
        Chart.register(...registerables);
        fetch(this.urlValue).then((response) => {
            // [fetching dynamically the data required for the chart]
        })
            .then((body) => {
                new Chart(this.canvasTarget, {
                    plugins: [ChartJSDataLabel],
       // [Rest of the chart configuration and JS content]
```
